### ISSUE TITLE
is it possible to make the 1.18 version compatible with wild world ?

### ISSUE THREAD

**Issue by Chuunkyz** [Luligabi1/MagicFungi#37]
wild world has cave biomes that are incompatible with the mod
i know this is a problem mostly with wild world, but this mod is the only mod that adds modded worldgen so i would be really happy if this mod could be compatible with it...

**Comment by Luligabi1** [comment]
Wild world borks the mushroom gen? All 1.18 versions don't have the Host Biome yet, so I fail to see how wild world would be incompatible... what exactly is the incompatbility? Do mushrooms not gen on Wild World's biomes or/and caves or they don't gen whatsoever? I need more info.

**Comment by Chuunkyz** [comment]
when loading a world, there's a datapack error when using this mod with wild world

[20:04:13] [Render thread/INFO]: [biomes] Found 0 tags, added 0 objects, removed 0 objects
[20:04:13] [Render thread/INFO]: Mixing in Cave Biomes...
[20:04:13] [Render thread/INFO]: Applied 5557 biome modifications to 99 of 99 new biomes in 518.2 ms
[20:04:13] [Render thread/INFO]: Mixing in Cave Biomes...
[20:04:13] [Render thread/WARN]: Failed to load datapacks, can't proceed with server load
java.lang.IllegalStateException: Feature order cycle found, involved biomes: [net.minecraft.class_1959@718e5a5, net.minecraft.class_1959@6b0789aa]
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.12) ~[?:?]
	at net.minecraft.world.biome.source.BiomeSource.method_39525(BiomeSource:130) ~[?:?]
	at net.minecraft.world.biome.source.BiomeSource.<init>(BiomeSource:65) ~[?:?]
	at net.minecraft.world.biome.source.BiomeSource.<init>(BiomeSource:58) ~[?:?]
	at net.minecraft.world.biome.source.MultiNoiseBiomeSource.<init>(MultiNoiseBiomeSource:54) ~[?:?]
	at net.minecraft.world.biome.source.MultiNoiseBiomeSource$Preset.getBiomeSource(MultiNoiseBiomeSource:131) ~[?:?]
	at net.minecraft.world.biome.source.MultiNoiseBiomeSource$Instance.getBiomeSource(MultiNoiseBiomeSource:97) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.world.biome.source.MultiNoiseBiomeSource.method_28459(MultiNoiseBiomeSource:42) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.mapBoth(Either.java:33) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.DataResult.map(DataResult.java:110) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.MapDecoder$4.decode(MapDecoder.java:94) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.MapCodec$1.decode(MapCodec.java:34) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.codecs.KeyDispatchCodec.lambda$null$1(KeyDispatchCodec.java:67) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.codecs.KeyDispatchCodec.lambda$decode$2(KeyDispatchCodec.java:58) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.codecs.KeyDispatchCodec.decode(KeyDispatchCodec.java:56) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.MapDecoder.lambda$compressedDecode$0(MapDecoder.java:52) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.Decoder.parse(Decoder.java:18) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.codecs.FieldDecoder.decode(FieldDecoder.java:29) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.MapCodec$1.decode(MapCodec.java:34) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$7.decode(RecordCodecBuilder.java:407) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.codecs.KeyDispatchCodec.lambda$null$1(KeyDispatchCodec.java:67) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.codecs.KeyDispatchCodec.lambda$decode$2(KeyDispatchCodec.java:58) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.codecs.KeyDispatchCodec.decode(KeyDispatchCodec.java:56) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.MapDecoder.lambda$compressedDecode$0(MapDecoder.java:52) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.Decoder.parse(Decoder.java:18) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.codecs.FieldDecoder.decode(FieldDecoder.java:29) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.MapCodec$1.decode(MapCodec.java:34) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$3.decode(RecordCodecBuilder.java:249) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.MapDecoder.lambda$compressedDecode$0(MapDecoder.java:52) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.Decoder.parse(Decoder.java:18) ~[datafixerupper-4.0.26.jar:?]
	at me.shedaniel.someforgepatchesported.LenientUnboundedMapCodec.lambda$decode$3(LenientUnboundedMapCodec.java:46) ~[someforgepatchesported-1.0.2.jar:?]
	at java.util.stream.ReduceOps$1ReducingSink.accept(ReduceOps.java:80) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:667) ~[?:?]
	at me.shedaniel.someforgepatchesported.LenientUnboundedMapCodec.decode(LenientUnboundedMapCodec.java:42) ~[someforgepatchesported-1.0.2.jar:?]
	at me.shedaniel.someforgepatchesported.LenientUnboundedMapCodec.lambda$decode$8(LenientUnboundedMapCodec.java:64) ~[someforgepatchesported-1.0.2.jar:?]
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.0.26.jar:?]
	at me.shedaniel.someforgepatchesported.LenientUnboundedMapCodec.decode(LenientUnboundedMapCodec.java:64) ~[someforgepatchesported-1.0.2.jar:?]
	at com.mojang.serialization.Decoder$2.decode(Decoder.java:63) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.Codec$2.decode(Codec.java:71) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.util.dynamic.RegistryCodec.decode(RegistryCodec:33) ~[?:?]
	at com.mojang.serialization.Decoder$2.decode(Decoder.java:63) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.Codec$2.decode(Codec.java:71) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.Decoder.parse(Decoder.java:18) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.codecs.FieldDecoder.decode(FieldDecoder.java:29) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.MapCodec$1.decode(MapCodec.java:34) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$5.decode(RecordCodecBuilder.java:324) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.MapDecoder.lambda$compressedDecode$0(MapDecoder.java:52) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.Decoder$1.decode(Decoder.java:49) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.Codec$2.decode(Codec.java:71) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.Decoder.parse(Decoder.java:18) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.client.MinecraftClient.method_31126(MinecraftClient:1954) ~[?:?]
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.client.MinecraftClient.method_31125(MinecraftClient:1954) ~[?:?]
	at net.minecraft.client.MinecraftClient.createIntegratedResourceManager(MinecraftClient:2157) ~[?:?]
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient:2003) ~[?:?]
	at net.minecraft.client.MinecraftClient.createWorld(MinecraftClient:1947) ~[?:?]
	at net.minecraft.client.gui.screen.world.CreateWorldScreen.createLevel(CreateWorldScreen:278) ~[?:?]
	at net.minecraft.client.gui.screen.world.CreateWorldScreen.method_19922(CreateWorldScreen:214) ~[?:?]
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget:40) ~[?:?]
	at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget:16) ~[?:?]
	at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget:121) ~[?:?]
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement:27) ~[?:?]
	at net.minecraft.client.Mouse.method_1611(Mouse:94) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:491) ~[?:?]
	at net.minecraft.client.Mouse.onMouseButton(Mouse:94) ~[?:?]
	at net.minecraft.client.Mouse.method_22686(Mouse:165) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101) ~[?:?]
	at net.minecraft.client.Mouse.method_22684(Mouse:165) ~[?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem:220) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1145) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:733) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:238) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]

**Comment by Chuunkyz** [comment]
also, removing dimension fix (someforgepatchesported) changes nothing, the issue isn't due to that mod !

**Comment by Luligabi1** [comment]
This issue is definitively on WW's end. Magic Fungi does no modification of world gen via datapacks whatsover and the world gen it does is purely via vanilla's PlacedFeatures. It's most likely an incompatibility similar to what I've had reported with terralith not being able to gen modded content into the world :/

Either way, I'd suggest not to use Magic Fungi on 1.18 atm due to the lack of the Host Biome until 1.18.2 comes around. Happy Holidays
